# The name of the workflow as it will appear in the "Actions" tab on GitHub
name: RegisterApp CI Pipeline

# The "on" keyword defines the events that trigger the workflow
on:
  # Specifies that this workflow runs on a "pull_request" event
  pull_request:
    # Limits the execution to pull requests being opened or synchronized
    types: [ opened, synchronize ]

# The "jobs" section groups all the tasks to be executed
jobs:
  ai-code-review-google:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Google Gemini AI Code Review
        uses: AleksandrFurmenkovOfficial/ai-code-review@v0.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}
          ai_provider: 'openai'
          openai_api_key: ${{ secrets.GOOGLE_API_KEY }}
          openai_model: 'gpt-4-turbo'
